### PR TITLE
Search Framework Fixes | 7.2 | LRDOCS-7232

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7232, hey Tibor, probably the only thing you really need to look at is the edit I made to the code in the statistical aggregations article.

### CODE REVIEW

**Comment by rbohl** [comment]
Here's the code editing commit: https://github.com/lipusz/liferay-docs/pull/54/commits/4765b6ea9fc920e5e5d36d7adc5bcc381c329503

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
Looks good to me. Thanks @rbohl ! :+1:

**Comment by rbohl** [comment]
Forwarded: https://github.com/sez11a/liferay-docs/pull/4478

**Pull request closed without merging**
