### PR TITLE
LRDOCS-6019 and LRDOCS-6227

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-6019, https://issues.liferay.com/browse/LRDOCS-6227, hopefully noth of these tickets are taken care of by this pull.

### CODE REVIEW

**Comment by lipusz** [comment]
Hey Russ,

Can you please re-send this by putting all the related commits to the top? That's why I said you in December that rebase should be used instead of merging which makes very hard to review the changes.

Create a new branch off of 7.1.x and cherry-pick the related commits for LRDOCS-6227 and LRDOCS-6019.

Thanks! @rbohl

**Comment by lipusz** [comment]
You could also talk to Rich and discuss to try following the same approach we use in the portal repos: people are never merging, but rebase-ing. And PRs should never contain unrelated commits to help the reviewer easily overview the changes.

**Comment by rbohl** [comment]
Hey Tibor, wouldn't the proper procedure in this case be to 1-- Checkout a branch based on 7.1.x, 2--pull your branch, 3--make my commits on top of it, 4-- git rebase 7.1.x ?

That's what I did. Looks like there's a strange history though.

https://github.com/liferay/liferay-docs/compare/7.1.x...rbohl:LRDOCS-6227-es-settings-7.1

I'll keep looking into it.

**Comment by rbohl** [comment]
@lipusz, nevermind, it's better now. It was simply that I hadn't update my local 7.1.x. I'll reopen.

**Comment by lipusz** [comment]
Thank you Russ! @rbohl

**Comment by lipusz** [comment]
feels-so-good

@rbohl

**Pull request closed without merging**
