### PR TITLE
search 7.1.x | elasticsearch 7 | LRDOCS-8195

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-8195

Tested steps. This is the basic setup--please advise how we should add upgrade
and security.

### CODE REVIEW

**Comment by lipusz** [comment]
Just copy paste the existing upgrading to ES7 article should be enough.

**Comment by lipusz** [comment]
Or what specific upgrade/security instructions are you looking for?

**Comment by lipusz** [comment]
We need pretty much the same as https://help.liferay.com/hc/en-us/articles/360035444872-Upgrading-to-Elasticsearch-7 for 7.2

**Comment by lipusz** [comment]
I thought you were just going to copy paste the same articles from 7.2.x

**Comment by rbohl** [comment]
> I thought you were just going to copy-paste/sync the same articles from 7.2.x. thinking

Did we talk about that? :sweat_smile: 

> Is there a problem with that approach?

Nope. I can do that.

**Comment by lipusz** [comment]
To me that's the most straightforward approach with minimal additional work.

**Comment by lipusz** [comment]
Thank you Russ

**Pull request closed without merging**
