### PR TITLE
LRDOCS-5890, ES 6.5 reorganized

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5890, reorganized.

### CODE REVIEW

**Comment by lipusz** [comment]
Weird: it detects conflicts... :-/

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
I can't rebase it to latest 7.1.x :-(

**Comment by rbohl** [comment]
hmm, let me merge 7.1.x locally and see if it complains. if so i will resolve the conflicts and resend.

**Comment by rbohl** [comment]
superceded by https://github.com/lipusz/liferay-docs/pull/20

**Pull request closed without merging**
