### PR TITLE
7.2 | LPS-88114 and LPS-88116, the Explain feature/api

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-88114, https://issues.liferay.com/browse/LPS-88116, made a new 7.2 article for the Search Insights widget.

### CODE REVIEW

**Comment by rbohl** [comment]
Added a commit that clarifies that the response string is now included in the Insights widget.

**Comment by rbohl** [comment]
Bump ;)

**Comment by lipusz** [comment]
it's on my list, don't panic. :-)

I've finished the multi-language search today.

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
We should add note that it's supported by the Elasticsearch connector only. @rbohl

**Comment by lipusz** [comment]
:question: I'm confused by the "desired outcome" of the stories and what I can actually see on latest master: https://issues.liferay.com/browse/LPS-86087?focusedCommentId=1705627&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1705627

**Comment by lipusz** [comment]
I've some additional questions to André: https://issues.liferay.com/browse/LPS-86087?focusedCommentId=1705627&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1705627

**Comment by rbohl** [comment]
See https://github.com/lipusz/liferay-docs/pull/24/commits/1b4a594f586d4bd49a751956cc0145009b733956 for review edits

**Comment by lipusz** [comment]
:+1: Nice, ready to send to Rich. Thanks, Russ! @rbohl

**Comment by rbohl** [comment]
forwarded here: https://github.com/sez11a/liferay-docs/pull/3924

**Pull request closed without merging**
