### PR TITLE
LPS-90869, aggregations intro and base code article

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LPS-90869, with new section base on outline, and new article for code usage--istantiate, construct, and add aggregations to a search request, then execute the search.

### CODE REVIEW

**Comment by lipusz** [comment]
Can you please add `[](id=id)` stuff to the headers for linking?

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by rbohl** [comment]
Generated headers :+1:

**Comment by lipusz** [comment]
Hey Russ, @rbohl 

Will you add https://github.com/rbohl/liferay-docs/blob/LPS-91190-cardinality-aggregation/draft.markdown to this? Or we're merging to master separately?

**Comment by rbohl** [comment]
Hey @lipusz , so we can do whatever we want for reviewing these, but when they get sent to Rich we have to be careful about sending huge PRs. Those aren't appreciated. Combining everything on aggregations might not get too huge though. So, if it makes it easier for us, we can combine - if it's gonna get huge, we should keep separate. Let me know what you think.

**Comment by lipusz** [comment]
Reviewed, made minor edits. I've nothing to add for now.
Sent back as https://github.com/liferay/liferay-docs/pull/500.

Thanks, Russell! :+1:

**Pull request closed without merging**
