### PR TITLE
Search 7.1 | Elasticsearch 6.8 support | LRDOCS-7453

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7453, this tries to get us up to 6.8 for Liferay 7.1. The section on Choosing a Search Engine needs help, as I mentioned in the ticket. Let me know if you think anything else is needed.

### CODE REVIEW

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
Hey Russell,

Do you think you could incorporate the relevant changes of https://github.com/rbohl/liferay-docs/pull/156 into this PR for 7.1.x (so basically to clearing-out the TLS/SSL configs for security for 6.8) or you'd prefer to do it under those tickets in a separate PR for 7.1.x (and 7.0.x)?

**Comment by lipusz** [comment]
Looks good to me. :+1:

**Comment by rbohl** [comment]
Yeah, I'll wait to include the relevant 6.8 changes after we hash out what we need, if any.

**Pull request closed without merging**
