### PR TITLE
LRDOCS-7605, Take 2 | Queries and Filters

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7605, I left the step-by-step code examples generic, but more concrete in the complete code example. I also added just a touch of information on processing the search response, based on my recent experience getting a search request built and executed in the script console. cc @joshuacords

### CODE REVIEW

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
I'm making some edits on https://github.com/lipusz/liferay-docs/tree/pr-68-search-7.2-queries-and-filters-fix_LRDOCS-7605.

**Comment by lipusz** [comment]
There are a couple of syntax errors in the code. I'll resend to you with my changes.

**Comment by lipusz** [comment]
Hey Russ, @rbohl 

I've created a boilerplate SB app with no DB tables that holds the search dev example as a simple remote service we can invoke through JSONWS. See
https://github.com/lipusz/liferay-portal-ee/tree/search-dev-docs-7.2.x
https://github.com/lipusz/liferay-portal-ee/tree/search-dev-docs-7.2.x/modules/apps/portal-search-dev-docs
https://github.com/lipusz/liferay-portal-ee/blob/search-dev-docs-7.2.x/modules/apps/portal-search-dev-docs/portal-search-dev-docs-service/src/main/java/com/liferay/portal/search/dev/docs/service/impl/PortalSearchServiceImpl.java#L66

The app is based off of 7.2.0 so it can be deployed on any 7.2 versions (hopefully), but I have only tested it yet on latest 7.2.x.

:man_technologist: With this we can test the example code easier in the future. You just need to fetch this branch, build the app and deploy onto 7.2. Once it's resolved, go to `/api/jsonws`, select `portal_search` as context and you will see the APIs available to invoke. If you run `gradlew eclipse` on the root of the app you can also import the source to Eclipse if you want debug the code.

The current snippet suffered from a lot of syntax errors and also it used a deprecated field we no longer index since https://issues.liferay.com/browse/LPS-70724. I'll update doc and send back to you tomorrow with some additional changes.

Cheers,
Tibi

**Comment by rbohl** [comment]
Excellent! I was thinking of a module for testing this (I imagine some of the syntax errors were me translating the groovy script i wrote into Java--sorry). Glad we have one to use now.

And thanks for mentioning that viewCount is a deprecated field! That's good to know. I was just looking for something to demonstrate pulling data out of the Document.

**Comment by lipusz** [comment]
I don't say this format is the ultimate way to track our dev examples, but I'm 99% that we need an app/modules we
* have full control over im terms of maintenance, can commit changes with no or very short review cycle
* can build and test continuously to catch early if they needed to be adapted to eventual API/SPI changes

**Comment by rbohl** [comment]
I'd be happy to follow this approach, but I'm gonna have to use the liferay-learn _template module once we move it over there. Anyway, if there are modules in liferay-portal-ee and I can simply translate code to liferay-learn, it will help. And, no matter what, as evidenced by the first attempt at this, we need to be able to test our code before we publish it in the docs.

**Comment by lipusz** [comment]
https://github.com/rbohl/liferay-docs/pull/160

**Pull request closed without merging**
