### PR TITLE
LRDOCS-5831, devguide, 7.1: search intro and ES logging article

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-5831 We decided to move the article on adjusting the embedded ES server's logging to the developer guide, since we state in no uncertain terms that the embedded Elasticsearch server is not for production use. That means we need a search intro article. I adapted the beginning of the 7.0 article (which is way too long, so I did not copy a lot of it in). Please review the intro article to make sure it's accurate.

### CODE REVIEW

**Comment by rbohl** [comment]
This is the specific commit I'd like reviewed: https://github.com/lipusz/liferay-docs/pull/17/commits/c45f7213bae054cecb2117d58fd98d1a37026b99

**Comment by lipusz** [comment]
Looks good to me. :+1:

**Comment by rbohl** [comment]
@lipusz regarding the URL for the `liferay-type-mappings.json`, I linked to the path in the src code because I figured the elasticsearc6 modules would be in the source code zip files, but not the solr7 modules. So the only way you can look at Solr 7 source code is if you have the liferay-portal repo cloned or if you look on github. Is that a correct assumption? I can mention the src zip file downloads and provide a link, too.

**Comment by rbohl** [comment]
Sent for publication: https://github.com/sez11a/liferay-docs/pull/3727

**Pull request closed without merging**
