### PR TITLE
LRDOCS-4884 search results

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4884, Search Results.

### CODE REVIEW

**Comment by lipusz** [comment]
**Started reviewing...** :mag:

**Comment by lipusz** [comment]
Hi Russel,

Please my findings, suggestions.

*Suggest edit*:

`04-search-results/01-display-settings.markdown`:
```diff
-Pagination Delta : Set the number of results to display per results page. Defaults to 20.
+Pagination Delta : Set the number of results to display per results page. Defaults to 20 unless you customized the `search.container.page.default.delta` property in your portal-ext.properties.
```

`04-search-results/02-results-behavior.markdown`:
"Permissions and Search Result" section
I'd extend the explanation *The first permissions check happens* with "pre-filtering" and *" a second, last-second permissions check is"* with "post-filtering".

"Initial Permissions Checking" section
1. The name of the configuration options should be bold or distinguished somehow from the plain text.
2.
> The second setting, Permissions Term Limit, limits the number of permission search clauses added to the search query before this level of permission checking is aborted. Permission checking then relies solely on the final permission filtering described below.

>Why would you want to limit the number of permissions clauses in the search query? Performance. Too many search terms in a query can make the search engine time out.

I'd mention that too many clauses can happen with users with too many site/organization memberships like admins.

"Highlighting" section
1.
```difff
-Highlgihting is disabled in the widget configuration screen.
+Highlgihting can be disabled in the widget configuration screen.
```
2. summary + highlighting: Maybe we could also explain that ideally, asset indexers are generating the summary from a special generated *field* the search engine returns called `snippet`: basically it's the relevant part of the text where the keywords the user was searching for were found and best matched (if applicable).

Thanks, :+1: 
Tibor

**Comment by rbohl** [comment]
@lipusz I just want to understand the last part regarding the snippet field, summaries, and highlighting, a little better. Tell me if this is correct, or where I am wrong.

1.  Developer tells the search api which indexed fields to include in the summary.

2.  Asset creator creates an Asset

3.  End User searches for a keyword that returns the asset.

4.  Results returned in order of relevance.

5.  If the keyword is present in any of the summary-enabled fields of a returned document, that particular snippet of the indexed content is presented in the summary, and the matched keyword is highlighted (if enabled).

Is that about right?

**Comment by rbohl** [comment]
I'll conclude the Summary section like this:

>The asset developer determines which fields are summary-enabled, but there's logic invoked at search time that determines precisely which part of the summary fields to display. For example, a `content` field can have a lot of text, but the summary doesn't show it all. Instead, it shows just a snippet of the field's text. If the keyword searched for is present in the summary field, that portion of the field is used in the summary. In addition, the matching keyword is highlighted in the summary.

**Comment by lipusz** [comment]
Sounds good. Maybe "it shows just a **relevant** snippet of the field's text." would be even clearer. :+1: 

Thanks, Russ!

**Pull request closed without merging**
